apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: kubernetes_practice
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes_practice
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80