apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: kubernetes_practice
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes_practice
        tier: frontend
    spec:
      containers:
      - name: rust-practice
        image: 926972041025.dkr.ecr.ap-northeast-1.amazonaws.com/rust-practice:0469da3e3022f0e8deb76d4f8bfe88daa5d409fd
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80